name: Ubuntu Bionic / Linux

on: [push, pull_request]

jobs:
  test-gazebo9-melodic:

    runs-on: ubuntu-18.04
    container: osrf/vrx:current

    steps:
      - uses: actions/checkout@v2
        with:
          path: /tmp
      - name: Install base dependencies
        run: |
          sudo apt update;
          sudo apt-get -y install cppcheck protobuf-compiler;
  
      - name: Static code checking
        run: cd /tmp/vrx;
             sh tools/code_check.sh;

      - name: Set up workspace
        run: |
          mkdir -p /tmp/vrx_ws/src;
          ln -s /tmp/vrx /tmp/vrx_ws/src;
          cd /tmp/vrx_ws

      - name: Build
        run: |
          source /opt/ros/melodic/setup.bash;
          catkin_make -j1

      - name: Run tests
        run: catkin_make run_tests -j1
