name: Release to DockerHub
on: [push]
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    container: 
      image: osrf/vrx:current
    env:
      registry: osrf/vrx
    strategy:
      matrix:
        image_name: ['vrx']
    steps:
      - run: sudo chown -R `whoami`:`whoami` .
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Docker
        if: ${{ success() }}
        run: |
          sudo apt update;
          sudo apt-get install -y apt-transport-https \
                                  ca-certificates \
                                  curl \
                                  gnupg-agent \
                                  software-properties-common;
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable";
          sudo apt-get update;
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io;

      - name: Run build script
        shell: bash
        if: ${{ success() }}
        run: |
          ls -a;
          sudo docker/build.bash . -t ${{ matrix.image_name }}:current

      - name: Login to docker hub
        if: ${{ success() }}
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to docker
        if: ${{ success() }}
        uses: actions-hub/docker@master
        env:
          NAME: ${{ matrix.image_name }}
          TAG: ${{ env.registry }}:current
        with:
          args: push ${IMAGE_TAG}
